### ISSUE TITLE
Array handling

### ISSUE THREAD

**Issue by joshgachnang** [FlourishHealth/ferns-api#61]
# Problem: 
When updating an item in an array right now, you need to pass in the entire array to update that field. This increases the chance of collisions and isn't a very nice UX.

Example:

```
const user = new Schema({
    nicknames: [String]
});

// Adding a nickname
PUT /users/62b4c652f7e9e4f037db7080
{nicknames: ["Bob", "Bobert"]}

// Updating a nickname
PUT /users/62b4c652f7e9e4f037db7080
{nicknames: ["Rob", "Bobert"]}

// Removing nicknames
PUT /users/62b4c652f7e9e4f037db7080
{nicknames: ["Bob"]}
```

# Solution
An improved interface that is REST-y:
```
// Adding a nickname
POST /users/62b4c652f7e9e4f037db7080/nicknames
{data: "Bob"}
OR
{data: ["Bob", "Bobert"]}

// Updating a nickname
PUT /users/62b4c652f7e9e4f037db7080/nicknames/0
{data: "Rob"}

// Deleting a nickname
DELETE /users/62b4c652f7e9e4f037db7080/nicknames/1
```

If the array is an array of subschemas, we can either use the index or the ObjectId as the path:
```
const nickname = new Schema({
    name: String,
    public: Boolean
});
const user = new Schema({
    nicknames: [nickname]
});

// Updating a nickname
PUT /users/62b4c652f7e9e4f037db7080/nicknames/0
{data: "Rob"}

OR

PUT /users/62b4c652f7e9e4f037db7080/nicknames/62b4c9877c13878920343312
{data: "Rob"}

// Deleting a nickname
DELETE /users/62b4c652f7e9e4f037db7080/nicknames/1

OR

DELETE /users/62b4c652f7e9e4f037db7080/nicknames/62b4c9877c13878920343312

```

# Open questions
Should we enforce `data` as the key for the body? Allow bare POST/PUTs?

**Comment by kjkurtz** [comment]
Agreed with Dan, nix the `data` requirement and use the key that you'd expect to use (`nickname` in the example) and maintain a JSON body that way.

From the example, it looks like it could be a "related entity" or just an array within an entity.

Using the ObjectId in the path looks good if it is a "related entity", but I don't think we should use array index. In the case of editing a value in an existing array, I think we need to POST, PUT, or DELETE the entire array if we are doing an update.

Indexes should remain consistent, but if the data you have is stale (ex. a value has been removed since originally fetching it), that index is no longer valid which would make using array index not RESTful. Granted, this has the same risk we have now with inserting the entire array and overwriting any changes that have happened since fetching.
